version: '3.8'

services:
  # IAA Frontend (React)
  frontend:
    build:
      context: ./iaa-feedback-system
      dockerfile: Dockerfile.production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped

  # IAA Backend (Rust)
  backend:
    build:
      context: ./iaa-backend
      dockerfile: Dockerfile.production
    ports:
      - "8000:8000"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
      - ENVIRONMENT=production
      - DATABASE_URL=postgresql://postgres.ltsosvqwyqqzmfnepchd:anshious%232004@aws-0-ap-south-1.pooler.supabase.com:6543/postgres
      - JWT_SECRET=iaa-production-super-secure-jwt-secret-key-2024
      - CORS_ORIGINS=http://frontend:3000,https://your-domain.com
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: iaa-network
