[tool.poetry]
name = "iaa-backend"
version = "0.1.0"
description = "IAA Backend API"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "3.11.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
